/**********TERMINAL IN USE**********/
export const OPEN_MODAL_TEMINAL_USE = 'OPEN_MODAL_TEMINAL_USE';
export const CLOSE_MODAL_TEMINAL_USE = 'CLOSE_MODAL_TEMINAL_USE';
export const OPEN_MODAL_TEMINAL_EDIT = 'OPEN_MODAL_TEMINAL_EDIT';
export const CLOSE_MODAL_TEMINAL_EDIT = 'CLOSE_MODAL_TEMINAL_EDIT';

/**********Library IN USE**********/
export const OPEN_LIBRARY_MODAL_CREATE = 'OPEN_LIBRARY_MODAL_CREATE';
export const CLOSE_LIBRARY_MODAL_CREATE = 'CLOSE_LIBRARY_MODAL_CREATE';
export const OPEN_LIBRARY_MODAL_EDIT = 'OPEN_LIBRARY_MODAL_EDIT';
export const CLOSE_LIBRARY_MODAL_EDIT = 'CLOSE_LIBRARY_MODAL_EDIT';