/**********TERMINAL IN USE**********/
export const OPEN_MODAL_TEMINAL_USE = 'OPEN_MODAL_TEMINAL_USE';
export const CLOSE_MODAL_TEMINAL_USE = 'CLOSE_MODAL_TEMINAL_USE';
export const OPEN_MODAL_TEMINAL_EDIT = 'OPEN_MODAL_TEMINAL_EDIT';
export const CLOSE_MODAL_TEMINAL_EDIT = 'CLOSE_MODAL_TEMINAL_EDIT';
export const GET_ALL_COMMAND = 'GET_ALL_COMMAND'

/**********Library IN USE**********/
export const OPEN_LIBRARY_MODAL_CREATE = 'OPEN_LIBRARY_MODAL_CREATE';
export const CLOSE_LIBRARY_MODAL_CREATE = 'CLOSE_LIBRARY_MODAL_CREATE';
export const OPEN_LIBRARY_MODAL_EDIT = 'OPEN_LIBRARY_MODAL_EDIT';
export const CLOSE_LIBRARY_MODAL_EDIT = 'CLOSE_LIBRARY_MODAL_EDIT';
export const GET_ALL_LIBRARIES = 'GET_ALL_LIBRARIES';

/**********LOADING**********/
export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';


/**********TODOLIST**********/
export const SET_LIST_TODO = 'SET_LIST_TODO'
export const SET_LIST_TODO_BY_ID = 'SET_LIST_TODO_BY_ID';
export const SET_TITLE_TODO = 'SET_TITLE_TODO'
export const OPEN_FORM_EDIT_TODOLIST = 'OPEN_FORM_EDIT_TODOLIST'
export const CLOSE_FORM_EDIT_TODOLIST = 'CLOSE_FORM_EDIT_TODOLIST'

/**********WORK**********/
export const GET_ALL_WORK = 'GET_ALL_WORK'
export const CHANGE_TYPE_WORK = 'CHANGE_TYPE_WORK'
export const OPEN_WORK_MODAL_EDIT = 'OPEN_WORK_MODAL_EDIT';
export const CLOSE_WORK_MODAL_EDIT = 'CLOSE_WORK_MODAL_EDIT';

/**********USER**********/
export const GET_ALL_USER = 'GET_ALL_USER'
export const OPEN_USER_MODAL_EDIT = 'OPEN_USER_MODAL_EDIT';
export const CLOSE_USER_MODAL_EDIT = 'CLOSE_USER_MODAL_EDIT';

/**********COMMENT**********/
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'